apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s 
      evaluation_interval: 15s 
      scrape_timeout: 20s
    alerting:
      alertmanagers:
      - static_configs:
        - targets: []

      

    rule_files:

    scrape_configs:
    - job_name: 'prometheus'
   

      static_configs:
      - targets: ['prom-svc0:9090']
 
    - job_name: 'rhelvm'

      static_configs:
      - targets: ['192.168.56.101:9100']
   
    - job_name: 'docker'
      static_configs:
      - targets: ['192.168.99.103:1234']    
        labels:
          env: test
       
